swagger: '2.0'
info:
  version: 1.0.0
  title: API for Carnegie Mellon Success Predictor
  description: Various endpoints for communicating with a server
    for predicting the success of CMU applicants
tags:
- name: Predictors
paths:
  /predict:
    get:
      tags:
      - Predictors
      description: |
        Predicts the final grade of a CMU applicant through various metrics.
        Metrics were chosen for two goals:
        - accurately represent an applicant's academic background, and 
        - Provide additional context on factors and conditions outside of the applicant's control.
        
        Thus, we chose the following fields to consider initially:
        *Academic Background*: amount of time studied, failures, absences, activites
        *Additional environment context*: access to internet, mother's education, father's education.

        *(Note: We chose not to include fields related to personal relationships because
        we felt that it would be a breach of privacy and also not as informative.)*
      parameters:
        - name: studytime
          in: query
          type: integer 
          minimum: 1
          maximum: 4
          required: true
          description: |
            Weekly study time 
            1 - less than 2 hours
            2 - 2 to 5 hours
            3 - 5 to 10 hours
            4 - greater than 10 hours
        - name: failures
          in: query
          type: integer
          minimum: 1
          maximum: 4
          required: true
          description: |
            Number of past class failures
            n if 1 <= n <= 3, otherwise 4
        - name: absences
          in: query
          type: integer
          mininmum: 0
          maximum: 93
          required: true
          description: The number of absences of this applicant between 0 and 93
        - name: activities
          in: query
          type: boolean
          required: true
          description: Whether or not the applicant participates in extracurricular activities
        - name: internet
          in: query
          type: boolean
          required: true
          description: Whether or not the applicant has internet access at home
        - name: medu
          in: query
          type: integer
          required: true
          minimum: 0
          maximum: 4
          description: |
            Mother's education
            0 - none
            1 - primary education (4th grade)
            2 – 5th to 9th grade
            3 - secondary education
            4 – higher education
        - name: fedu
          in: query
          type: integer
          required: true
          minimum: 0
          maximum: 4
          description: |
            Father's education
            0 - none
            1 - primary education (4th grade)
            2 – 5th to 9th grade
            3 - secondary education
            4 – higher education
      responses:
        200:
          description: Successfully returned a grade prediction
          schema: 
            $ref: '#/definitions/Grade'
        400:
          description: Bad request. Either required query parameters are not all present or a query parameter's value is invalid

definitions:
  Grade:
    type: integer
    minimum: 0
    maximum: 20
    example: 17
